---
kind: pipeline
type: docker
name: test-pr

platform:
  os: linux
  arch: amd64

steps:
- name: identify-runner
  image: alpine:3.14.2
  commands:
  - echo $DRONE_RUNNER_NAME

- name: initialize
  image: grafana/build-container:1.4.3
  commands:
  - echo test
  - mkdir -p bin
  - curl -fL -o bin/grabpl https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v2.4.6/grabpl
  - chmod +x bin/grabpl
  - yarn cache dir
  - yarn install --frozen-lockfile --no-progress
  environment:
    DOCKERIZE_VERSION: 0.6.1
    YARN_CACHE_FOLDER: /cache/yarn
  volumes:
  - name: cache
    path: /cache
  depends_on:
  - restore-cache-yarn
  - restore-cache-node-modules

- name: codespell
  image: grafana/build-container:1.4.3
  commands:
  - "echo -e \"unknwon\nreferer\nerrorstring\neror\niam\nwan\" > words_to_ignore.txt"
  - codespell -I words_to_ignore.txt docs/
  depends_on:
  - restore-cache-yarn

- name: shellcheck
  image: grafana/build-container:1.4.3
  commands:
  - ./bin/grabpl shellcheck
  depends_on:
  - restore-cache-yarn

- name: restore-cache-yarn
  pull: always
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  settings:
    backend: gcs
    bucket: test-julien
    cache_key: test123
    json_key:
      from_secret: tf_google_credentials
    local_root: /cache
    mount:
    - yarn
    restore: true
  volumes:
  - name: cache
    path: /cache
  depends_on:
  - clone

- name: restore-cache-node-modules
  pull: always
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  settings:
    backend: gcs
    bucket: test-julien
    json_key:
      from_secret: tf_google_credentials
    mount:
    - node_modules
    restore: true
  depends_on:
  - clone

- name: lint-backend
  image: grafana/build-container:1.4.3
  commands:
  - make gen-go
  - ./bin/grabpl lint-backend --edition oss
  environment:
    CGO_ENABLED: 1

- name: test-frontend
  image: grafana/build-container:1.4.3
  commands:
  - yarn run ci:test-frontend
  environment:
    TEST_MAX_WORKERS: 50%
    YARN_CACHE_FOLDER: /cache/yarn
  depends_on:
  - restore-cache-yarn
  - restore-cache-node-modules
  - initialize

- name: build-frontend
  image: grafana/build-container:1.4.3
  commands:
  - ./bin/grabpl build-frontend --jobs 8 --no-install-deps --edition oss --build-id ${DRONE_BUILD_NUMBER} --no-pull-enterprise
  environment:
    YARN_CACHE_FOLDER: /cache/yarn
  depends_on:
  - test-frontend

- name: rebuild-cache-yarn
  pull: always
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  settings:
    backend: gcs
    bucket: test-julien
    cache_key: yarn
    json_key:
      from_secret: tf_google_credentials
    local_root: /cache
    mount:
    - yarn
    rebuild: true
  volumes:
  - name: cache
    path: /cache
  when:
    event:
    - pull_request
  depends_on:
  - build-frontend

- name: rebuild-cache-node-modules
  pull: always
  image: jduchesnegrafana/drone-cache:v1.2.0-rc0-dirtytest
  settings:
    backend: gcs
    bucket: test-julien
    json_key:
      from_secret: tf_google_credentials
    mount:
    - node_modules
    rebuild: true
  when:
    event:
    - pull_request
  depends_on:
  - build-frontend

volumes:
- name: cache
  temp: {}

trigger:
  event:
  - pull_request

---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: secret
name: github_token

get:
  path: infra/data/ci/github/grafanabot
  name: pat

---
kind: secret
name: drone_token

get:
  path: infra/data/ci/drone
  name: machine-user-token

---
kind: secret
name: tf_google_credentials

get:
  path: infra/data/ci/terraform/google
  name: credentials.json

---
kind: secret
name: access_key

get:
  path: infra/data/ci/test-drone-caching
  name: access-key

---
kind: secret
name: secret

get:
  path: infra/data/ci/test-drone-caching
  name: secret

---
kind: signature
hmac: 5bca2257833d33c19dccdd731cae601794ee280e33a5a1f842364655837d2f19

...
